### ISSUE TITLE
Develop test routines

### ISSUE THREAD

**Issue by AndreaIdini** [AndreaIdini/Schroedinger#2]
- [x] Compare box at zero potential with trigonometric wave function.
- [x] Compare eigenfunction of the harmonic oscillator with Hermite polynomials
- [x] ... for different sizes
- [ ] Compare with Numerical potential respect to a professional solution

**Comment by GabrielePisciotta** [comment]
- [x] Choose a test framework ( Boost.Test | Google Test | ... )
- [x] Create .cpp test module
- [x] Split the test code from the pruduction code
- [x] Setup continuous integration

**Comment by GabrielePisciotta** [comment]
There's the need to make more meaningful tests.

**Comment by GabrielePisciotta** [comment]
Refactored tests. Need more tests for Basis and Potentials

**Comment by GabrielePisciotta** [comment]
Look at #19
