### ISSUE TITLE
Check for compilation on Windows / OSX

### ISSUE THREAD

**Issue by GabrielePisciotta** [AndreaIdini/Schroedinger#21]

**Comment by GabrielePisciotta** [comment]
Now it compiles on Windows with MinGW , except for test executable which requires std::hermite of C++17.

**Comment by AndreaIdini** [comment]
The same on OSX, I fixed the compilation for g++-7 but using clang does not cut it. 
Even setting `--std=c++17` could not find `std::hermite.`

Is a compiler problem, being clang and visual c++ not fully C++17  compliant.

**Comment by GabrielePisciotta** [comment]
# You can now compile also on Windows and OS X #

We tested it using:

**Linux**: gcc > 6
**OS X**: the last CLang 
**Windows**: Intel C++ Compilers (on Visual Studio 17)
