### ISSUE TITLE
Implement Base class

### ISSUE THREAD

**Issue by AndreaIdini** [AndreaIdini/Schroedinger#22]
The base class is arguably the most critical part of the program.
A detailed description of a proposed implementation is available in the [wiki](https://github.com/AndreaIdini/Schroedinger/wiki/Classes:-Basis)

**Comment by AndreaIdini** [comment]
Implementing Continuous basis.
The base class have to be modified to account for a coordinate vector of one index and remove the potential, which will have a basis passed by the constructor.

**Comment by AndreaIdini** [comment]
In the Potential object, there is no use in passing a coordinate AND a basis. The basis IS the coordinate (or the set of coordinates).

**Comment by AndreaIdini** [comment]
> 
> l'istanza _(di base)_ deve essere accessibile ovunque, e l'istanza stessa deve essere la stessa sempre.
> Se creo BaseCartesiana1, non ho bisogno della possibilita' di cambiarla.
> Pero' magari posso voler creare BaseSferica2 e farci dei giochetti che poi ti spieghero'... a volte si usa (io ad esempio uso due basi per i calcoli di reazioni).
> 
> Uno puo' anche fare un codice a base singola, su questo non e' un problema, solo una occasione mancata magari... pero' bisogna poterla istanziare con dei parametri, perche' quanto vuoi grande lo spazio e' diverso ad ogni calcolo ovviamente. Altrimenti non avrebbe proprio senso fare un oggetto classe (e in tal senso un po' mi sfugge a questo punto il ruolo dei singoletti).
> 
> In ogni caso deve essere accessibile ovunque, perche' io voglio attivare il solver senza definire lo scope ogni volta della base, divento un po' scemo...
> Pero' vabbeh, se no si passa la base come oggetto, ma non mi ricordo che problema ci fosse in tal caso... era una questione probabilmente un po' formale... Probabilmente che un oggetto deve avere sempre la stessa forma per essere accessibile, invece con il singoletto puoi sbizzarrirti di piu'  poiche' alla fine e' tutto e solo gestito tramite metodi...
> Quindi metti che vuoi passare da una rappresentazione 1D a 3D, con il singoletto puoi usare lo stesso metodo in entrambi i casi per accedere ai vettori di base, con un oggetto devi saperlo prima se andare a guardare gli elementi di un vettore, o di piu' vettori o un vettore di vettori...
>

**Comment by AndreaIdini** [comment]
Singleton structure for Base class might be not ideal.
The good is that:
- singleton are accessed from everywhere. Since the pervasive nature of basis, this is convenient to avoid passing the basis in **every! single! call!** of a routine in the program.
- singleton doesn't allow to touch constructors once instantiated, that is what we want to protect the basis generator (however, is probably a quite an academic point, we can protect all the parameter, and nobody will call a constructor overwriting a basis in the middle of a calculation).
**The problem right now is that:**
 the Base class must be instantiated starting from parameters (I have to be free to choose how large the space is) and [singleton doesn't like that](https://stackoverflow.com/questions/4203634/singleton-with-parameters).

Singleton for Manager of basis is evaluated right now.

**Comment by GabrielePisciotta** [comment]
We could create a BasisManager as a singleton class, and let Base to be a normal class. 

- BasisManager will let you create new basis through a parametric method (like a factory, in order to create various type of Base). In this way there'll be no more problem with constructors _(e.g.: BasisManager.getInstance().create( Base::baseType::3DsphericalHarmonic )_
- Each Base created will be accessible everywhere through BasisManager, that store their reference in a list _(e.g.: BasisManager.getInstance().getBasisList())_. This could also be easily expanded in the future to read basis directly from disk/network...


![untitled diagram](https://user-images.githubusercontent.com/13509050/43010616-34cf0378-8c41-11e8-805b-959df5aa8713.jpg)

**Comment by GabrielePisciotta** [comment]
BasisManager has been implemented.

**Comment by AndreaIdini** [comment]
@GabrielePisciotta Can we be considered satisfied, now that you implemented a stub of 2D solution and passed basis everywhere?

**Comment by GabrielePisciotta** [comment]
@AndreaIdini 

> @GabrielePisciotta Can we be considered satisfied, now that you implemented a stub of 2D solution and passed basis everywhere?

For me it's ok, we can close the issue!
