### ISSUE TITLE
Implement potential reading from ASCII file

### ISSUE THREAD

**Issue by AndreaIdini** [AndreaIdini/Schroedinger#23]
Given an ASCII file for potential, e.g.,
``` 
0.0   2.1
0.2   2.2
0.4   2.7
...
20.0  0.01 
```
reads the potential and the basis mesh (implying either 1D or radial, for example)

**Comment by GabrielePisciotta** [comment]
It'd be better to read serialized Potential objects?

**Comment by AndreaIdini** [comment]
What do you mean by serialized?

The read is done line by line, in the future one could think about a routine that does addition of potentials, that is also useful (e.g. Coulomb potential from pointlike source + from a planar).

And this could be easily used also to read potentials in different regions or eventually parallelize reading...

**Comment by GabrielePisciotta** [comment]
Implemented
