### ISSUE TITLE
Investigate the possibility to use a MapReduce approach 

### ISSUE THREAD

**Issue by GabrielePisciotta** [AndreaIdini/Schroedinger#26]

**Comment by AndreaIdini** [comment]
MapReduce of what for what else?

**Comment by GabrielePisciotta** [comment]
MapReduce is a framework for constructing an algorithm that will be execute in parallel on a distributed database, redefining only a map() function to extract and filter data and a reduce() function to mixing them into the result. Maybe could be useful in the future.

**Comment by AndreaIdini** [comment]
For what I know, MapReduce works best on cluster to distribute the load over several machines in a robust way.
I don't see Schroedinger to be solved in a cluster. We could use acceleration on GPU, but I don't think map-reduce is the ideal way to approach the load distrubtion of an accelerator and CPU.
