### ISSUE TITLE
Include a log system

### ISSUE THREAD

**Issue by GabrielePisciotta** [AndreaIdini/Schroedinger#32]
We should use a proper library (I propose https://github.com/gabime/spdlog ) to manage logs. Have a look
at it, there are examples of how to use it and it's explained its flexibility.

This have to be included as an external module (as we did with googletest module), also modifying the main CMakeLists.txt in order to compile it.

**Comment by GabrielePisciotta** [comment]
Useful surveys:  [1](https://neutronsharc.blogspot.com/2016/12/choose-c-logging-library-im-recently.html), [2](http://lifewithdotnet.blogspot.com/2017/03/log-library-comparison.html).

**Comment by AndreaIdini** [comment]
In unit test modify the cout printing 
```
    std::cout << std::fixed << std::setprecision(2);
    std::cout << "Test completed" << std::endl;
    std::cout << "Energies: " << E_numerov << " " << E_analytic << std:: endl;
    std::cout << "num wf: " << numerov_Wf.at(0) << " " << numerov_Wf.at(numerov_Wf.size()/2) 
              << " " << numerov_Wf.at(numerov_Wf.size() - 1) << " " << std::endl;
    std::cout << "ana wf: " << analytic_Wf.at(0) << " " << analytic_Wf.at(analytic_Wf.size()/2)
              << " " << analytic_Wf.at(analytic_Wf.size()-1) << std::endl;
```

in order to be a debugging log
