### ISSUE TITLE
Bug in Numerov solver

### ISSUE THREAD

**Issue by GabrielePisciotta** [AndreaIdini/Schroedinger#37]
`WfTest.HarmonicOscillator` test, only on Windows, raises a "vector subscript out of range" error. 

![bug](https://user-images.githubusercontent.com/13509050/43641641-c388f5d6-9724-11e8-95fe-ffb6503db1cc.png)

**Comment by AndreaIdini** [comment]
Might be related to #44

**Comment by GabrielePisciotta** [comment]
This must be re-tested, maybe it doesn't exist anymore due to the changes done.
