### ISSUE TITLE
[Fix] First element of the potential vector is 0

### ISSUE THREAD

**Issue by GabrielePisciotta** [AndreaIdini/Schroedinger#44]
(Harmonic oscillator)
![graph](https://user-images.githubusercontent.com/13509050/52664545-93a84380-2f09-11e9-9b8a-effd51af6ac5.png)

**Comment by AndreaIdini** [comment]
Regarding `potential_values.push_back(1.0);` in `Numerov::findWavefunction` ass discussed in #43.

To urgently correct since in this way this fix is a memory leak, it adds values to Potential each time the Numerov routine is called (several time before finding the solution).

> what's this? it should be completely wrong.
> I understand that you are adding a 1.0 at the end of the potential, this is probably because of some mismanagement of vector positions. Be careful that numerov depends at the position -2, -1 respect to the search position. Position 0, 1 are fixed at start. Therefore, you should iterate for a number of steps equal to `nbox-2`. Try to print what values of potential are you actually using where you where having crashes.
> 
> Just for fun, what are you making is something:
> 
> * asymmetrical (in the case of center in 0, as in all of our tests)
> * discontinuous
> * discontinuous right at boundary
> 
> which is a complete mess physically. What would happen physically if this were possible in reality, is that over time you would accumulate wave function density (particles) at boundary due to tunnelling. Due to the small width and low and sharp potential this would generate a "quantum ratchet" effect that would completely wreck havoc to the thermodynamics of the system.

**Comment by GabrielePisciotta** [comment]
- [x] Fixed tricky fix that lead to a memory leak
- [x] Fixed potential starting at ~0
![graph](https://user-images.githubusercontent.com/13509050/52811099-8ff4f800-3094-11e9-99c5-6d19f3190e09.png)
