### ISSUE TITLE
Replace trapezoidal rule with a better one (math library)

### ISSUE THREAD

**Issue by GabrielePisciotta** [AndreaIdini/Schroedinger#46]

**Comment by AndreaIdini** [comment]
Numerov::trapezoidalRule may be substituted with a better library method (should be pretty fast and reliable as is).
Alternatively we could start developing a "Math" class (or submodule) with the common numerical functions such as bisection, trapezoidal...etc...

As in #43

**Comment by GabrielePisciotta** [comment]
Look #54
