### ISSUE TITLE
Implement boundary conditions in basis

### ISSUE THREAD

**Issue by AndreaIdini** [AndreaIdini/Schroedinger#48]
Implement boundary condition property, to be used in `Numerov`. I believe the best place to set the property is `basis`, while the setup in `Numerov` should be done when calling the `Numerov::Solve` method.

> This initialisation (of Numerov `wf[0]=0.; wf[1] = 0.1;` ndR) does not belong to the start of class, but to something that should be called before `findWavefunction`. That is, the setup of the boundary conditions, that should be in `solve` and `bisection`.
> Now bisection is too coupled with solved, so it cannot be generalized, so there is fine. (cf. later comment)

> _Originally posted by @AndreaIdini in https://github.com/Scienza/Schroedinger/diffs_

**Comment by mechanapoleon** [comment]
A brief comment. 
The spectrum of the Hamiltonian (i.e. the energy values) is tightly related to the boundary conditions. As a minimum viable product, we can just set them to be zero in the boundary, but in the end  they are to be given by the user.

**Comment by AndreaIdini** [comment]
Done
