### ISSUE TITLE
Fail multidimensional test

### ISSUE THREAD

**Issue by AndreaIdini** [AndreaIdini/Schroedinger#73]
The multidimensional test for harmonic oscillator does not work. The `state` has the correct energy, but the `wave function` keeps its 0s initialisation.

The code is an exact copy of the code in `main.cpp` that prints the wave function with good results! Might be a mishandling of pointers?

TODO: once fixed the wave function output, I will do multidimensional tests on Finite Well potential, and maybe higher eigenvalues options.

**Comment by GabrielePisciotta** [comment]
Tests now are green. Need to investigate the wavefunction problem.

**Comment by GabrielePisciotta** [comment]
The problem was in the initializing of the mesh. It must have certain values in order to have a convergence of the Numerov's method. @AndreaIdini please write something more about accepted values

**Comment by AndreaIdini** [comment]
We have investigated. We found that too small mesh points inside the finite well give problems but is not related to multidimensional solution.
Gabriele also implemented a visualisation of the bisection algorithm inside numerov to understand what happens iteration by iteration.
