### ISSUE TITLE
Implement a Class structure.

### ISSUE THREAD

**Issue by AndreaIdini** [AndreaIdini/Schroedinger#8]
Requisites to consider: 
- implementation of different bases (now is in cartesian 1D, one can be willing implement spherical, Bessel, cylindrical, multiD ...etc...) and potentials.
- different method of solution (stationary and time-dependent Schroedinger, relativistic)
- introducing different many--body nature of particles (fermions, bosons)
- possible expansion towards many--body and field--theory methods (MBPT, Coupled Cluster)...etc...

**Comment by AndreaIdini** [comment]
Follow [the project wiki](https://github.com/AndreaIdini/Schroedinger/wiki/Classes)

**Comment by AndreaIdini** [comment]
Potential class implemented

**Comment by GabrielePisciotta** [comment]
Basis classes implemented

**Comment by GabrielePisciotta** [comment]
@AndreaIdini the projects is now almost fully OOP. I think that this can be closed.

**Comment by AndreaIdini** [comment]
Now with Solver class and State class the project is finally OO.
